module.exports = {
  'Submit metadata form': function(browser) {
    browser
      .url('http://localhost:8000/metadata/add?tab=1')
      .waitForElementVisible('body', 1000)
      .setValue('.input-title input', 'Lorem Ipsum Dolor Sit Amet')
      .setValue('.input-number input', '02/02/2015')
      .setValue('.input-docType select', 'Perpres')
      .setValue('.input-publishedDate input', '2015-02-02')
      .setValue('.input-validDate input', '2015-02-02')
      .setValue('.input-siteUrl input', 'http://domain.net/link-to-siteurl')
      .setValue('.input-docUrl input', 'http://domain.net/link-to-docurl')
      .setValue('.input-description input', 'Lorem Ipsum Dolor Sit Amet')
      .click('.act-tabs .tab-optional')
      .setValue('input[name="altSiteUrl.0"]', 'http://altdomain.net/link-to-altsiteurl')
      .click('.add-altSiteUrl')
      .pause(1000)
      // .setValue('input[name="altSiteUrl.1"]', 'http://altdomain.net/link-to-altsiteurl')
      .setValue('input[name="altDocUrl.0"]', 'http://altdomain.net/link-to-altdocurl')
      .click('.add-altDocUrl')
      .pause(1000)
      // .setValue('input[name="altDocUrl.1"]', 'http://altdomain.net/link-to-altdocurl')
      // .setValue('input[name="creator.name"]', 'Kementerian Kehutanan dan Lingkungan Hidup')
      // .setValue('input[name="creator.type"]', 'kementerian')
      // .setValue('input[name="enactment.number"]', '02/02/2015')
      // .setValue('input[name="enactment.publishedDate"]', '2015-02-02')
      // .setValue('input[name="enactment.siteUrl"]', 'http://altdomain.net/link-to-altsiteurl')
      // .setValue('input[name="enactment.docUrl"]', 'http://altdomain.net/link-to-altdocurl')
      // .setValue('input[name="unappliedEffect.0.docNumber"]', '02/02/2015')
      // .setValue('input[name="unappliedEffect.0.status"]', 'mengganti')
      .click('.add-unappliedEffect')
      .pause(1000)
      // .setValue('input[name="unappliedEffect.1.docNumber"]', '02/02/2015')
      // .setValue('input[name="unappliedEffect.1.status"]', 'mengganti')
      .click('.act-tabs .tab-file')
      .click('.act-save')
      .assert.attributeContains('#fileupload', 'id', 'fileupload');
  }
};